### ISSUE TITLE
Sortování AMF souborů

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Openscad_stdlib#3]
Při generování AMF souborů mohou vznikat falešné změny, jen díky tomu, že AMF soubor nemá jednotně seřazené vertexy. V případě STL souborů tento problém řešíme použitím nástroje [stlsort](https://pypi.org/project/stlsort/). Pro formát AMF ale zřejmě takový nástroj neexistuje. 

Pokud se potvrdí, že tento problém skutečně vzniká i v nových verzích OpenSCADu, tak bude nutné takový nástroj vytvořit.

**Comment by roman-dvorak** [comment]
Toto issue vzniklo na základě mého podezření na tento problém. Bylo to v době, kdy jsem použivat nějaký starší OpenSCAD (cca 2019, nevím přesnou verzi) teď už mám rozfungovanou novejší verzi. Tak to otestuji znovu.

**Comment by JanKott** [comment]
Vytvořil jsem python skript, který sortuje AMF. Aktuálně tedy sortuje VERTICES a následně přečísluje odkazy ve VOLUMES. Problém je, že když následně sesortim i VOLUMES tak Slic3r vrací u některých souborů chyby: Unable to close loop having XX points.
Sortování VOLUMES je tedy zakomentované.

**Comment by kaklik** [comment]
A jak to sortování VOLUMES přesně funguje?  Podle tohoto https://en.wikipedia.org/wiki/Additive_manufacturing_file_format#Geometry_specification To chápu tak, že nelze nezávisle od sebe prohazovat VOLUMES a VERTICES.

**Comment by JanKott** [comment]
1) seřadim vertices
2) podle nového pořadí přepíšu id ve volumes
3) seřadim volumes

Příklad:
vertices = [[4,2,3], [7,1,5], [3,4,2]]
volumes = [[2,3,1], [1,2,3]]

Pořadí uvnitř závorek se nikdy nemění!

Krok 1: seřazené vertices tudíž jsou:
[[3,4,2], [4,2,3], [7,1,5]]

Krok 2: přečísluju volumes tak aby odazovaly na správné vertices:
[[3, 1, 2], [2,3,1]]

Krok 3: seřadim volumes:
[[2,3,1], [3,1,2]]

Po seřazení volumes začne slic3r vracet warningy. Nevidim tam žádnej problém kterej by to mělo způsobovat. Je otázka, jestli ty AMF nejsou chybné (2-manifold) a tim seřazenim se to jen neprojeví?

**Comment by kaklik** [comment]
Kdyby ty AMF obsahovaly 2-manifold chybu, tak by se tahle záležitost neprojevovala u všech modelů. 
Stává se to u všech modelů, kde provedeš seřazení VOLUMES?

**Comment by JanKott** [comment]
Jen u některých
