### ISSUE TITLE
Aktualizace dep souborů 

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Openscad_stdlib#5]
v dep souborech je problém, že je tam kokrétní generovaný soubor. Protože jeden makefile generuje STL, druhý generuje AMF a třetí generuje obojí.. Myslím, že by bylo lepší, kdyby tam byl vypsán zdrojový soubor, ze kterého to bylo generované. Protože tady bude záležet na spuštění makefilů aby se to vygenerovalo správně.
A úplně ideálně by se to mělo kontrolovat stáří více výstupů. Ne jen stl ale stl, amf, png, gcode.

**Comment by JanKott** [comment]
Uplně mi není jasné o co jde. V DEP souboru samozřejmě je zdrojový soubor, ze kterého je to vygenerované. Jsou tam napsány všechny soubory, které se pro generování použijí (čili dependencies).

Příklad:
```
../amf/WINDGAUGE_R03.amf: \
    configuration.scad \
    src/lib/copyFunctions.scad \
    src/lib/curvedPipe.scad \
    src/lib/maths.scad \
    src/lib/moreShapes.scad \
    src/lib/naca4.scad \
    src/lib/polyScrewThread_r1.scad \
    src/lib/vector.scad \
    src/WINDGAUGE_R03.scad \
    src/WINDGAUGE_R06.scad \
```

Rozumím tomu takto:

dám make

make se podívá, jestli je výsledek (AMF, PNG, STL) starší než jeho dependencies. Pokud ano, zavolá příkaz, který má nadefinovaný pro jeho sestavení.

To udělá pro každý výstup, který chceme sestavit (třeba u anemometru PNG závisí jen na STL, ale STL závisí na všech .scad dependencies).

**Comment by roman-dvorak** [comment]
Jde o to, že může existovat více makefilů, které budou z jednoho souboru vytvářet AMF, STL a PNG. Vznikne tento DEP který obsahuje výstupní soubor. A třeba pořadí AMF, STL a PNG bude jiné. Takže naposledy se vygeneruje STL a v prvním řádku .dep souboru nebude AMF ale STL. Čímž se nám ten soubor změnil a přitom obsahuje ty samé informace. 

Myslím, že na prvním řádku by měl být zdrojový soubor. Makefile zná, jak se výsledný soubor má jmenovat. Takže stáří souborů může porovnávat s ním. 

Jak zmiňuješ PNG, tak to je ještě jiná věc, protože pro něj je zdrojový soubor STL.

**Comment by JanKott** [comment]
Smysl použití více Makefile nechám stranou. Proč tedy každý TARGET nevytváří vlastní DEP soubor, pokud mají svoje dependencies?
Mám pocit, že se tu snažíme znásilnit make.
Jestli tomu dobře rozumim (nejsem na make zrovna expert), tak:
Make vezme TARGET, podívá se, jestli je starší, než jeho DEPENDENCIES a pokud ne, tak ho přebuilduje (zavolá příkazy pro daný target).

OpenSCAD logicky vytváří DEP soubor se seznamem DEPENDENCIES pro daný TARGET (čili AMF, nebo STL, nebo PNG podle toho co zrovna sestavuje).

Úplně správně by tedy podle mě bylo:
1) Renderovat AMF a pro něj vyrobit DEP soubor.
2) Renderovat STL a jako dependency mít AMF soubor (pokud je to jen na koukání v GITu).
3) Renderovat PNG a jako dependency mít AMF, nebo STL soubor (já mám u WINDGAUČe STL, protože to z něj renderuju).

Tim pádem mám jen jeden DEP soubor, protože STL a PNG jsou závislé na AMF.

**Comment by JanKott** [comment]
@kaklik @roman-dvorak 
Jaký na to máte názor?

**Comment by roman-dvorak** [comment]
V processor3D jsem tento problém nakonec vyřešil tak, že si závislosti procházím sám a hledám jejich změny. Na základě toho se rozhoduji jestli se mají bulidit nebo ne. To mi řeší tu křížovou závislost na generovaných souborech. 

dep soubory si trochu upravuji tak, aby to bylo univerzální nezávislé na targetu. A zároveň to sortím aby se ten soubor moc neměnil.

**Comment by roman-dvorak** [comment]
Další věc třeba je, že závislost má být i konfigurační soubor pro slic3r. Který doposud v deps nebyl zahrnut.

**Comment by JanKott** [comment]
To je ale závislost při slicování, ne při renderování. Když se změní konfigurační soubor pro slic3r tak rozhodně nemusim přerenderovat SCAD model. Taková závislost se asi dá do Makefile doplnit explicitně, protože se taky explicitně předkládá slic3ru.
